---
- name: Populate /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: '{{ wheel }}'
    mode: '0644'
  vars:
    col1: 16
    col2: "{{ groups.all | map('length') | max + (ansible_domain | length) + 2 }}"
    col3: "{{ groups.all | map('length') | max + 1 }}"
    fmt: "{:<{{ col1 }}} {:<{{ col2 }}} {:<{{ col3 }}}"