---
# - name: Add IP address of all hosts to all hosts
#   lineinfile:
#     dest: /etc/hosts
#     regexp: '.*{{ item }}$'
#     line: "{{ hostvars[item].ansible_host }} {{item}}"
#     state: present
#   when: hostvars[item].ansible_host is defined
#   with_items: "{{ groups.all }}"
# - name: debug hosts
#   debug:
#     msg: |
#       127.0.0.1       localhost.{{ ansible_domain }}          localhost
#       {% for item in groups.all %}
#       {{ hostvars[item].ansible_host }}      {{ hostvars[item].ansible_facts }}
#       {% endfor %}
#   vars:
#     col1: 16
#     col2: "{{ groups.all | map('length') | max + (ansible_domain | length) + 2 }}"
#     col3: "{{ groups.all | map('length') | max + 1 }}"
#     fmt: "{:<{{ col1 }}} {:<{{ col2 }}} {:<{{ col3 }}}"

- name: Populate /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: wheel
    mode: '0644'
  vars:
    col1: 16
    col2: "{{ groups.all | map('length') | max + (ansible_domain | length) + 2 }}"
    col3: "{{ groups.all | map('length') | max + 1 }}"
    fmt: "{:<{{ col1 }}} {:<{{ col2 }}} {:<{{ col3 }}}"