---
- name: Set instance hostname
  hostname:
    name: "{{ inventory_hostname }}.{{ ansible_site }}.{{ ansible_root_domain }}"
  register: hostname
- name: Remove hostname line from /etc/rc.conf # The above block will write it to /etc/rc.conf.d/hostname on FreeBSD
  lineinfile:
    path: /etc/rc.conf
    regexp: '^hostname='
    state: absent
  when:
    - ansible_facts['distribution'] == "FreeBSD"
- name: Reboot if hostname changed
  reboot:
    reboot_timeout: 300
    connect_timeout: 30
    msg: "Rebooting to apply new hostname"
  when: hostname.changed