---
- name: Create dictionary with computed hostname for each host
  set_fact:
    all_hostnames: '{{ all_hostnames | 
      default({}) | 
      combine({ 
        (item + "." + hostvars[item].ansible_site + "." + hostvars[item].ansible_root_domain): {
          "ip": hostvars[item].ansible_host,
          "aliases": [item]
        }
      }) }}'
  with_items: '{{ groups["all"] }}'
  when: 
    - hostvars[item].ansible_host is defined
    - hostvars[item].ansible_site is defined
    - hostvars[item].ansible_root_domain is defined
- name: Populate /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: '{{ wheel }}'
    mode: '0644'
