---
- name: Load a variable file based on the OS type, or a default if not found.
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
        - default.yml
      paths:
        - 'vars'
- name: Load facts from SSM parameter store
  set_fact:
    ssm_parameters: "{{ ssm_parameters 
      | default({}) 
      | combine({
        item: lookup(
          'amazon.aws.aws_ssm', 
          '/homelab/{{ ansible_site }}/{{ item }}', 
          region=aws_ssm_parameter_region, 
          profile=aws_ssm_parameter_profile
        )
      }) }}"
  loop: "{{ ssm_parameter_names }}"
- name: Include tasks/hostname.yml
  include_tasks: tasks/hostname.yml
  when: manage_hostname
- name: Include tasks/hosts.yml
  include_tasks: tasks/hosts.yml
  when: manage_hosts_file
- name: Include tasks/users.yml
  include_tasks: tasks/users.yml
- name: Include tasks/os/{{ansible_os_family}}.yml
  include_tasks: tasks/os/{{ansible_os_family}}.yml
- name: Include tasks/packages.yml
  include_tasks: tasks/packages.yml
  when: manage_base_packages
- name: Include tasks/services.yml
  include_tasks: tasks/services.yml
  when: manage_services
- name: Include tasks/qemu.yml
  include_tasks: tasks/qemu.yml
  when: 
    - "'QEMU' in ansible_facts.processor | join(' ')"
- name: Include tasks/nfs_mounts.yml
  include_tasks: tasks/nfs_mounts.yml
  when: nfs_mounts is defined and nfs_mounts | length > 0

- name: Include tasks/iscsi_disks.yml
  include_tasks: tasks/iscsi_disks.yml
  when: iscsi_disks is defined and iscsi_disks | length > 0