---
- name: Install required base packages
  package:
    name: '{{ base_packages | default([]) }}'
    state: latest
- name: Configure sudo for wheel
  template:
    src: sudoers/wheel.j2
    dest: '{{ sudoers_dir }}/{{ wheel }}'
    owner: root
    group: '{{ wheel }}'
    mode: '0600'