---
- name: Install sudo
  package:
    name: sudo
    state: present
- name: Configure sudo for wheel
  template:
    src: sudoers/wheel.j2
    dest: '{{ sudoers_dir }}/{{ wheel }}'
    owner: root
    group: '{{ wheel }}'
    mode: '0600'
- name: Install vim
  package:
    name: vim
    state: present
- name: Install htop
  package:
    name: htop
    state: present
- name: Install rsync
  package:
    name: rsync
    state: present
