---
- name: Ensure qemu-guest-agent is installed on VMs
  package:
    name: qemu-guest-agent
    state: present
- name: Enable qemu-guest-agent service
  service:
    name: qemu-guest-agent
    enabled: true
- name: Start qemu-guest-agent service
  service:
    name: qemu-guest-agent
    state: started