---
- name: Install Apache
  pkgng:
    name: apache24
    state: present

- name: Create logs directory
  file:
    path: /var/log/apache24
    state: directory
    mode: 0755

- name: Enable Apache service
  service:
    name: apache24
    enabled: true

- name: Create custom error pages
  copy: 
    src: '{{ item }}'
    dest: '/usr/local/www/apache24/{{ item | basename }}'
    mode: 0644
  with_fileglob:
    - error_pages/*

- name: Create autoindex directory
  file:
    path: /usr/local/www/apache24/autoindex
    state: directory
    mode: 0755

- name: Copy autoindex templates
  copy:
    src: "apache/{{ item }}"
    dest: "/usr/local/www/apache24/autoindex/{{ item }}"
    mode: 0644
  with_items:
    - style.css
    
- name: Install TLS certificate
  include_role: 
    name: install-cert
  vars:
    web_server_user: www
    web_server_group: www
    web_services:
      - apache24

- name: Create sites directories
  file:
    path: '/usr/local/www/sites/{{ item.domain_name }}/www'
    state: directory
    owner: mirror
    group: mirror
    mode: '0755'
  loop: '{{ sites }}'
  loop_control:
    label: '{{ item.domain_name }}'

- name: Configure Apache
  template:
    src: apache/httpd.conf.j2
    dest: /usr/local/etc/apache24/httpd.conf
    owner: root
    group: wheel
    mode: '0644'
  notify: 
    - restart apache

- name: Start Apache service
  service:
    name: apache24
    state: started