---
- name: Install nginx
  pkgng:
    name: nginx
    state: present
- name: Create logs directory
  file:
    path: /var/log/nginx
    state: directory
    mode: 0755
- name: Enable nginx service
  service:
    name: nginx
    enabled: true
- name: Mount an NFS volume
  ansible.posix.mount:
    src: "{{ webroot_nfs_server }}:{{ webroot_nfs_prefix }}"
    path: "{{ webroot_local_dir }}"
    opts: rw,nosuid
    state: mounted
    fstype: nfs
- name: Create custom error pages
  copy: src='{{ item }}' dest='/usr/local/www/nginx/{{ item | basename }}' mode=0644
  with_fileglob:
    - error_pages/*
- name: Install TLS certificate
  include_role: 
    name: install-cert
  vars:
    web_server_user: www
    web_server_group: www
    web_services:
      - nginx
- name: Configure nginx
  template:
    src: nginx/nginx.conf.j2
    dest: /usr/local/etc/nginx/nginx.conf
    owner: root
    group: wheel
    mode: '0644'
  notify: 
    - restart nginx
- name: Start service nginx
  service:
    name: nginx
    state: started