---
- name: Configure motd
  template:
    src: motd.j2
    dest: /etc/motd.template
    owner: root
    group: wheel
    mode: '0644'
  notify: 
    - restart motd
  when:
    - ansible_facts['distribution'] == "FreeBSD"