---
- name: restart cupsd
  service:
    name: cupsd
    state: restarted

- name: restart samba
  service:
    name: samba
    state: restarted

- name: restart avahi
  service:
    name: avahi-daemon
    state: restarted
