---
- name: restart expense_analysis
  service: name=expense_analysis state=restarted

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart nginx
  service: name=nginx state=restarted

- name: validate nginx configuration
  command: nginx -t -c /usr/local/etc/nginx/nginx.conf
  changed_when: false
