---
- name: Group 'jwhouse'
  group:
    name: jwhouse
    state: present
    gid: 222830
- name: User 'jwhouse'
  user:
    name: jwhouse
    comment: "Jacob House"
    shell: /bin/sh
    group: jwhouse
    groups: wheel
    append: false
    home: /home/jwhouse
    create_home: yes
    uid: 222830
    password: '*************'
- name: User 'jwhouse' authorized key
  authorized_key:
    user: jwhouse
    state: present
    exclusive: true
    key: '{{ item }}'
  with_file:
    - public_keys/jwhouse/jacobhouse-desktop.pub
    - public_keys/jwhouse/bruno.pub