---
- name: Group 'ngallant'
  group:
    name: ngallant
    state: present
    gid: 213815
- name: User 'ngallant'
  user:
    name: ngallant
    comment: "Noah Gallant"
    shell: /bin/sh
    group: ngallant
    groups: '{{ wheel }}'
    append: false
    home: /home/ngallant
    create_home: yes
    uid: 213815
    password: '*************'