---
- name: Install Plex
  pkgng:
    name: plexmediaserver
    state: present
- name: Enable Plex service
  service:
    name: plexmediaserver
    enabled: true
- name: Start Plex service
  ansible.builtin.service:
    name: plexmediaserver
    state: started
