all:
  children:
    lemarchant:
      children:
        mirrors:
          hosts:
            mirror:
              ansible_host: 10.174.32.5
        dns_servers:
          hosts:
            dns01:
              ansible_host: 10.174.32.9
            dns02:
              ansible_host: 10.174.32.10
          vars:
            dns_forwarders:
              - 1.1.1.1
              - 1.0.0.1
      vars:
        ansible_site: lemarchant
        ansible_ssh_private_key_file: ~/.ssh/lemarchant
        ansible_site_addresses:
          lan: 10.174.0.0/23
          openvpn: 10.174.2.0/24
          vpn: 10.174.3.0/24
          management: 10.174.4.0/23
          work: 10.174.6.0/24
          iot: 10.174.7.0/24
          lab: 10.174.32.0/19
  vars:
    ansible_root_domain: jacobhouse.ca