all:
  children:
    laptop:
      hosts:
        MacBook-Pro-de-Jacob: 
          ansible_host: 10.174.0.45
          owner: jwhouse
          ansible_user: jwhouse
    lemarchant:
      children:
        unmanaged:
          children:
            nas:
              hosts:
                ritchie:
                  ansible_host: 10.174.9.8
        managed:
          children:
            orchestrator:
              hosts:
                isengard:
                  ansible_host: 10.174.12.130
            shlink:
              hosts:
                impulse:
                  ansible_host: 10.174.12.67
              vars:
                ssm_parameter_names:
                  - shlink-database-credentials
                  - certificate-reader-ssh-private-key
                shlink_domain: go.jwfh.ca
                shlink_qr_code_logo: https://jwfh.ca/icons/icon-512x512.png
            postgres:
              hosts:
                dahlia:
                  ansible_host: 10.174.12.48
              vars:
                ssm_parameter_names:
                  - 'expense-analysis-database-credentials'
                  - 'expense-analysis-dev-database-credentials'
                  - 'expense-analysis-jhdev-database-credentials'
                  - 'expense-analysis-ngdev-database-credentials'
                  - 'shlink-database-credentials'
                  - 'tandoor-database-credentials'
                postgres_allowed_subnets:
                  dev:
                    - 10.174.0.0/23
                    - 10.174.12.0/22
                  prod:
                    - 10.174.12.0/22
            cloudflared:
              hosts:
                razor:
                  ansible_host: 10.174.8.19
              vars:
                ssm_parameter_names:
                  - cloudflared-tunnel-token
            squid:
              hosts:
                zephyr:
                  ansible_host: 10.174.3.17
            # backup_orchestrator:
            #   hosts:
            #     sonic:
            #       ansible_host: 10.174.x.x
            seedbox:
              hosts:
                vortex:
                  ansible_host: 10.174.3.16
                apollo:
                  ansible_host: 10.174.8.241
            tandoor:
              hosts:
                waffle:
                  ansible_host: 10.174.12.68
            poudriere:
              hosts:
                scarlet:
                  ansible_host: 10.174.12.145
                  poudriere_conf_zpool: poudriere
                  poudriere_cert: false
            bastion:
              hosts:
                blaster:
                  ansible_host: 10.174.8.16
            mailer:
              hosts:
                domino:
                  ansible_host: 10.174.12.160
            mirror:
              hosts:
                muffin:
                  ansible_host: 10.174.12.64
              vars:
                ssm_parameter_names:
                  - certificate-reader-ssh-private-key
            plex:
              hosts:
                pixel:
                  ansible_host: 10.174.12.96
            netboot:
              hosts:
                megatron:
                  ansible_host: 10.174.12.112
            ldap:
              hosts:
                gizmo:
                  ansible_host: 10.174.12.34
            homepage:
              hosts:
                scooby:
                  ansible_host: 10.174.12.65
                bowser:
                  ansible_host: 10.174.12.66
              vars:
                ssm_parameter_names:
                  - certificate-reader-ssh-private-key
            cicd_controller:
              hosts:
                papillon:
                  ansible_host: 10.174.12.144
            cicd_agent:
              hosts:
                velvet:
                  ansible_host: 10.174.12.47
            expense_analysis_app:
              hosts:
                shadow:
                  ansible_host: 10.174.12.69
                  expense_analysis_git_ref: python
                  database_credentials_paramter_name: expense-analysis-database-credentials
                  app_configuration_paramter_name: expense-analysis-dev-app-configuration
                  ssm_parameter_names:
                    - expense-analysis-database-credentials
                    - expense-analysis-deployer-ssh-private-key
                    - expense-analysis-dev-app-configuration
                storm:
                  ansible_host: 10.174.12.70
                  expense_analysis_git_ref: python
                  database_credentials_paramter_name: expense-analysis-dev-database-credentials
                  app_configuration_paramter_name: expense-analysis-dev-app-configuration
                  ssm_parameter_names:
                    - expense-analysis-dev-database-credentials
                    - expense-analysis-deployer-ssh-private-key
                    - expense-analysis-dev-app-configuration
            dns:
              hosts:
                pookie:
                  ansible_host: 10.174.12.8
                roller:
                  ansible_host: 10.174.12.9
              vars:
                dns_forwarders:
                  - 1.1.1.2
                  - 1.0.0.2
            internal_haproxy:
              hosts:
                ratchet:
                  ansible_host: 10.174.12.16
              vars:
                ssm_parameter_names:
                  - certificate-reader-ssh-private-key
            external_haproxy:
              hosts:
                arcee:
                  ansible_host: 10.174.8.17
              vars:
                ssm_parameter_names:
                  - certificate-reader-ssh-private-key
            certbox:
              hosts:
                bumblebee:
                  ansible_host: 10.174.12.128
              vars:
                ssm_parameter_names:
                  - cloudflare-acme-account-token
            compute:
              hosts:
                granite:
                  ansible_host: 10.174.13.0
                basalt:
                  ansible_host: 10.174.12.129
            nextcloud:
              hosts:
                piston:
                  ansible_host: 10.174.12.113
      vars:
        ansible_site: lemarchant
        ansible_user: skylord
        ansible_ssh_private_key_file: ~/.ssh/lemarchant
        aws_ssm_parameter_region: ca-central-1
        aws_ssm_parameter_profile: '{{ ansible_site }}-ssm-reader'
        ansible_site_addresses:
          lan: 10.174.0.0/23
          openvpn: 10.174.2.0/24
          vpn: 10.174.3.0/24
          management: 10.174.4.0/23
          work: 10.174.6.0/24
          iot: 10.174.7.0/24
          dmz: 10.174.8.0/24
          san: 10.174.9.0/24
          prod: 10.174.12.0/22
        ansible_prod_subnets:
          10.174.12.0/29: reserved
          10.174.12.8/29: dns
          10.174.12.16/28: proxy
          10.174.12.32/28: directory
          10.174.12.48/28: database
          10.174.12.64/27: web
          10.174.12.96/28: media
          10.174.12.112:/28: file
          10.174.12.128/28: misc
          10.174.12.144/28: cicd
          10.174.12.160/29: mail
          10.174.12.168/29: unreserved
          10.174.12.176/28: unreserved
          10.174.12.192/26: unreserved
          10.174.13.0/24: noah
          10.174.14.0/23: unreserved
  vars:
    ansible_root_domain: jacobhouse.ca
