all:
  children:
    lemarchant:
      children:
        unmanaged:
          children:
            nas:
              hosts:
                ritchie:
                  ansible_host: 10.174.9.8
        managed:
          children:
            # backup_orchestrator:
            #   hosts:
            #     sonic:
            #       ansible_host: 10.174.12.194
            bastion:
              hosts:
                blaster:
                  ansible_host: 10.174.8.8
            mirror:
              hosts:
                muffin:
                  ansible_host: 10.174.12.64
            plex:
              hosts:
                pixel:
                  ansible_host: 10.174.12.96
            netboot:
              hosts:
                megatron:
                  ansible_host: 10.174.12.129
            ldap:
              hosts:
                gizmo:
                  ansible_host: 10.174.12.34
            homepage:
              hosts:
                scooby:
                  ansible_host: 10.174.12.65
                bowser:
                  ansible_host: 10.174.12.66
            cicd-controller:
              hosts:
                papillon:
                  ansible_host: 10.174.12.144
            dns:
              hosts:
                pookie:
                  ansible_host: 10.174.12.8
                roller:
                  ansible_host: 10.174.12.9
              vars:
                dns_forwarders:
                  - 1.1.1.2
                  - 1.0.0.2
            internal-haproxy:
              hosts:
                ratchet:
                  ansible_host: 10.174.12.16
            external-haproxy:
              hosts:
                arcee:
                  ansible_host: 10.174.8.9
            acme:
              hosts:
                bumblebee:
                  ansible_host: 10.174.12.192
            compute:
              hosts:
                granite:
                  ansible_host: 10.174.13.0
      vars:
        ansible_site: lemarchant
        ansible_user: skylord
        ansible_ssh_private_key_file: ~/.ssh/lemarchant
        ansible_site_addresses:
          lan: 10.174.0.0/23
          openvpn: 10.174.2.0/24
          vpn: 10.174.3.0/24
          management: 10.174.4.0/23
          work: 10.174.6.0/24
          iot: 10.174.7.0/24
          dmz: 10.174.8.0/24
          san: 10.174.9.0/24
          prod: 10.174.12.0/19
  vars:
    ansible_root_domain: jacobhouse.ca
