all:
  children:
    lemarchant:
      children:
        unmanaged:
          children:
            nas:
              hosts:
                ritchie:
                  ansible_host: 10.174.32.128
        managed:
          children:
            backup_orchestrator:
              hosts:
                sonic:
                  ansible_host: 10.174.32.194
            bastion:
              hosts:
                blaster:
                  ansible_host: 10.174.32.17
            mirror:
              hosts:
                muffin:
                  ansible_host: 10.174.32.64
            plex:
              hosts:
                pixel:
                  ansible_host: 10.174.32.96
            netboot:
              hosts:
                megatron:
                  ansible_host: 10.174.32.129
            ldap:
              hosts:
                gizmo:
                  ansible_host: 10.174.32.34
            homepage:
              hosts:
                scooby:
                  ansible_host: 10.174.32.65
                bowser:
                  ansible_host: 10.174.32.66
            dns:
              hosts:
                pookie:
                  ansible_host: 10.174.32.8
                roller:
                  ansible_host: 10.174.32.9
              vars:
                dns_forwarders:
                  - 1.1.1.1
                  - 1.0.0.1
            haproxy:
              hosts:
                ratchet:
                  ansible_host: 10.174.32.16
            traefik:
              hosts:
                blaster:
                  ansible_host: 10.174.32.17
            acme:
              hosts:
                bumblebee:
                  ansible_host: 10.174.32.192
      vars:
        ansible_site: lemarchant
        ansible_user: skylord
        ansible_ssh_private_key_file: ~/.ssh/lemarchant
        ansible_site_addresses:
          lan: 10.174.0.0/23
          openvpn: 10.174.2.0/24
          vpn: 10.174.3.0/24
          management: 10.174.4.0/23
          work: 10.174.6.0/24
          iot: 10.174.7.0/24
          lab: 10.174.32.0/19
  vars:
    ansible_root_domain: jacobhouse.ca
  hosts:
#    starscream:
#    ironhide:
#    arcee:
#    optimus:
#    galvatron:
#    wheeljack:
#    perceptor:
#    hotrod:
#    jazz:
#    tailgate:
