all:
  children:
    lemarchant:
      children:
        unmanaged:
          children:
            nas:
              hosts:
                ritchie:
                  ansible_host: 10.174.9.8
        managed:
          children:
            orchestrator:
              hosts:
                isengard:
                  ansible_host: 10.174.x.x
            group:
              hosts:
                dahlia:
                  ansible_host: 10.174.x.x
            group:
              hosts:
                impulse:
                  ansible_host: 10.174.x.x
            group:
              hosts:
                razor:
                  ansible_host: 10.174.x.x
            group:
              hosts:
                shadow:
                  ansible_host: 10.174.x.x
            group:
              hosts:
                storm:
                  ansible_host: 10.174.x.x
            group:
              hosts:
                velvet:
                  ansible_host: 10.174.x.x
            group:
              hosts:
                zephyr:
                  ansible_host: 10.174.x.x
            group:
              hosts:
                domino:
                  ansible_host: 10.174.x.x
            group:
              hosts:
                piston:
                  ansible_host: 10.174.x.x
            group:
              hosts:
                scarlet:
                  ansible_host: 10.174.x.x
            group:
              hosts:
                vortex:
                  ansible_host: 10.174.x.x
            # backup_orchestrator:
            #   hosts:
            #     sonic:
            #       ansible_host: 10.174.12.194
            bastion:
              hosts:
                blaster:
                  ansible_host: 10.174.8.8
            mirror:
              hosts:
                muffin:
                  ansible_host: 10.174.12.64
            plex:
              hosts:
                pixel:
                  ansible_host: 10.174.12.96
            netboot:
              hosts:
                megatron:
                  ansible_host: 10.174.12.129
            ldap:
              hosts:
                gizmo:
                  ansible_host: 10.174.12.34
            homepage:
              hosts:
                scooby:
                  ansible_host: 10.174.12.65
                bowser:
                  ansible_host: 10.174.12.66
            cicd-controller:
              hosts:
                papillon:
                  ansible_host: 10.174.12.144
            dns:
              hosts:
                pookie:
                  ansible_host: 10.174.12.8
                roller:
                  ansible_host: 10.174.12.9
              vars:
                dns_forwarders:
                  - 1.1.1.2
                  - 1.0.0.2
            internal-haproxy:
              hosts:
                ratchet:
                  ansible_host: 10.174.12.16
            external-haproxy:
              hosts:
                arcee:
                  ansible_host: 10.174.8.9
            acme:
              hosts:
                bumblebee:
                  ansible_host: 10.174.12.128
            compute:
              hosts:
                granite:
                  ansible_host: 10.174.13.0
      vars:
        ansible_site: lemarchant
        ansible_user: skylord
        ansible_ssh_private_key_file: ~/.ssh/lemarchant
        ansible_site_addresses:
          lan: 10.174.0.0/23
          openvpn: 10.174.2.0/24
          vpn: 10.174.3.0/24
          management: 10.174.4.0/23
          work: 10.174.6.0/24
          iot: 10.174.7.0/24
          dmz: 10.174.8.0/24
          san: 10.174.9.0/24
          prod: 10.174.12.0/19
        ansible_prod_subnets:
          10.174.12.0/29: reserved
          10.174.12.8/29: dns
          10.174.12.16/28: proxy
          10.174.12.32/27: directory
          10.174.12.64/27: web
          10.174.12.96/27: media
          10.174.12.128/32: acme
          10.174.12.129/32: netboot
          10.174.12.130/31: unreserved
          10.174.12.132/30: unreserved
          10.174.12.136/29: unreserved
          10.174.12.144/28: cicd
          10.174.12.160/27: unreserved
          10.174.12.192/26: unreserved
          10.174.13.0/24: noah
          10.174.14.0/23: unreserved
  vars:
    ansible_root_domain: jacobhouse.ca
