---
- name: Install Postgres 17
  package:
    name: 
      - postgresql17-server 
      - postgresql17-client
      - postgresql17-contrib
    state: present
- name: Check if the Postgres data directory exists
  stat:
    path: /var/db/postgres/data17
  register: postgres_data
- name: Initialize Postgres
  shell: service postgresql initdb
  when: 'not postgres_data.stat.exists'
- name: Enable Postgres 17 service
  service:
    name: postgresql
    enabled: true
- name: Start Postgres 17 service
  service:
    name: postgresql
    state: started
- name: Gather Postgres configuration
  set_fact:
    database_config: "{{ 
      ssm_parameters.items() 
      | selectattr('0', 'match', '^.*-database-credentials$') 
      | map(attribute='1') 
      | map('from_json') 
      | selectattr('host', 'equalto', ansible_fqdn) 
      | list 
    }}"
  no_log: true
- name: Debug database config
  debug: msg='{{ database_config }}'

# - name: Create Postgres databases
#   postgresql_db:
#     name: "{{ ssm_parameters[item] | from_json |  community.general.json_query('database')  }}"
#     state: present
#   with_items: "{{ 
#     ssm_parameter_names | 
#     select('search', '^.*-database-credentials$') |
#     list }}"