---
- name: restart nginx
  service: name=nginx state=restarted
  when: web_server == 'nginx'

- name: validate nginx configuration
  command: nginx -t -c /usr/local/etc/nginx/nginx.conf
  changed_when: false
  when: web_server == 'nginx'

- name: reload nginx
  service: name=nginx state=reloaded
  when: web_server == 'nginx'
