ssm_parameter_names: []
package_manager_become: true
warning_comment:
  - THIS FILE IS MANAGED BY ANSIBLE. CE FICHIER EST GÉRÉ PAR ANSIBLE.
  - 
  - Any modifications to this file will be overwritten.
  - Toute modification apportée à ce fichier sera écrasée.

# Example NFS mounts
nfs_mounts: []
# - server: 192.168.1.10
#   remote_path: /srv/nfs/data
#   local_path: /mnt/data
#   options: rw,sync

# Example iSCSI disks
iscsi_disks: []
# - target: iqn.2023-01.com.example:storage.disk1
#   portal: 192.168.1.20
#   device: /dev/disk/by-path/ip-192.168.1.20:3260-iscsi-iqn.2023-01.com.example:storage.disk1-lun-0
#   local_path: /mnt/iscsi1
#   fstype: ext4
#   options: defaults
