---
- name: Install PHP and other dependencies
  pkgng:
    name: 
      - php84
      - php84-curl
      - php84-bcmath
      - php84-extensions
      - php84-gd
      - php84-intl
      - php84-pdo
      - php84-pdo_pgsql
      - php84-sockets
      - php84-zlib
      - unzip
    state: present
- name: Ensure the Shlink directory exists
  file:
    path: /usr/local/shlink
    state: directory
    owner: root
    group: '{{ wheel }}'
    mode: '0755'
- name: Check if Shlink installation exists
  stat:
    path: /usr/local/shlink/public/index.php
  register: shlink_index
- name: Unarchive a file that needs to be downloaded (added in 2.0)
  block:
    - name: Download Shlink release
      shell: fetch -o /tmp/shlink.zip https://github.com/shlinkio/shlink/releases/download/v4.4.4/shlink4.4.4_php8.4_dist.zip 
    - name: Extract Shlink release
      shell: tar --no-same-owner --no-same-permissions -xf /tmp/shlink.zip -s'|[^/]*/||' -C /usr/local/shlink
    - name: Clean up Slink release
      file:
        path: /tmp/shlink.zip
        state: absent
  when: 'not shlink_index.stat.exists'
- name: Write Shlink configuration file
  template:
    src: shlink/generated_config.php.j2
    dest: /usr/local/shlink/config/params/generated_config.php
    owner: root
    group: '{{ wheel }}'
    mode: '0640'
- name: Set permissions for Shlink data directory
  file: 
    path: /usr/local/shlink/data
    owner: root 
    group: '{{ wheel }}'
    mode: u=rwX,g=rX,o=rX
    recurse: true
- name: Install RoadRunner
  shell: 
    cmd: php ./vendor/bin/rr get --no-interaction --location bin/
    chdir: /usr/local/shlink
    creates: /usr/local/shlink/bin/rr
- name: Make RoadRunner executable
  file:
    path: /usr/local/shlink/bin/rr
    owner: root
    group: '{{ wheel }}'
    mode: '0755'
- name: Install Shlink rc script
  template:
    src: shlink/shlink.sh.j2
    dest: /usr/local/etc/rc.d/shlink
    owner: root
    group: '{{ wheel }}'
    mode: '0755'
- name: Check if Shlink has been initialized
  stat:
    path: /usr/local/shlink/data/.ansbile-init-complete
  register: shlink_init_flag
- name: Initialize Shlink
  shell: 
    cmd: ./vendor/bin/shlink-installer init
    chdir: /usr/local/shlink
  when: 
    - 'not shlink_init_flag.stat.exists'
  register: shlink_init
- name: Write init flag file
  shell: 'date -u "+%Y-%m-%dT%H:%M:%SZ" > /usr/local/shlink/data/.ansbile-init-complete'
  when:
    - shlink_init.changed