
---
- name: Compute node
  hosts: compute
  become: true
  vars_files:
    - "inventory/host_variables/{{ ansible_host }}.yml"
  roles:
    - jwfh-set-facts
    - base
    - user-server
    - generic-compute