---
# - name: Configure base operating system
#   hosts: managed
#   become: true
#   vars_files:
#     - "inventory/host_variables/{{ ansible_host }}.yml"
#   roles:
#     - base
# - name: Configure DNS Server (BIND9)
#   hosts: dns
#   become: true
#   vars_files:
#     - "inventory/host_variables/{{ ansible_host }}.yml"
#   roles:
#     - bind9
# - name: Configure SSH bastion
#   hosts: bastion
#   become: true
#   vars_files:
#     - "inventory/host_variables/{{ ansible_host }}.yml"
#   roles:
#     - bastion
#     - user-server
# - name: Configure compute nodes
#   hosts: compute
#   become: true
#   vars_files:
#     - "inventory/host_variables/{{ ansible_host }}.yml"
#   roles:
#     - user-server
#     - generic-compute
# - name: Configure public software mirror
#   hosts: mirror
#   become: true
#   gather_facts: true
#   vars_files:
#     - "inventory/host_variables/{{ ansible_host }}.yml"
#   vars:
#     webroot_nfs_server: ritchie
#     webroot_nfs_prefix: /mnt/default/mirror
#     webroot_local_dir: /mirror
#   roles:
#     - static-webserver
# - name: Configure portfolio site
#   hosts: homepage
#   become: true
#   gather_facts: true
#   vars_files:
#     - "inventory/host_variables/{{ ansible_host }}.yml"
#   vars:
#     webroot_nfs_server: ritchie
#     webroot_nfs_prefix: /mnt/default/services/homepage
#     webroot_local_dir: /homepage
#   roles:
#     - static-webserver
# - name: Configure Plex Media Server
#   hosts: plex
#   become: true
#   vars_files:
#     - "inventory/host_variables/{{ ansible_host }}.yml"
#   roles:
#     - plex
# - name: Configure CI/CD controller nodes
#   hosts: cicd_controller
#   become: true
#   vars_files:
#     - "inventory/host_variables/{{ ansible_host }}.yml"
#   roles:
#     - jenkins
# - name: Configure netboot servers
#   hosts: netboot
#   become: true
#   vars_files:
#     - "inventory/host_variables/{{ ansible_host }}.yml"
#   roles:
#     - pxeboot
# - name: Configure HAProxy reverse proxy servers for internal services
#   hosts: internal_haproxy
#   become: true
#   vars_files:
#     - "inventory/host_variables/{{ ansible_host }}.yml"
#   roles:
#     - haproxy
#   vars:
#     haproxy_is_external: false
#     haproxy_backend_services:
#       homepage:
#         mode: http
#         balance: roundrobin
#         port: 80
#         domain_name: jwfh.ca
#         servers: 
#           - gizmo.lemarchant.jacobhouse.ca
#           - bowser.lemarchant.jacobhouse.ca
#       plex:
#         mode: http
#         balance: sticky
#         port: 32400
#         domain_name: plex.jwfh.ca
#         servers: 
#           - pixel.lemarchant.jacobhouse.ca
#       jenkins:
#         mode: http
#         balance: sticky
#         port: 8080
#         domain_name: ci.jwfh.ca
#         servers:
#           - papillon.lemarchant.jacobhouse.ca
#       mirror:
#         mode: http
#         balance: roundrobin
#         port: 80
#         domain_name: mirror.jwfh.ca
#         servers: 
#           - muffin.lemarchant.jacobhouse.ca
- name: Configure HAProxy reverse proxy servers for external services
  hosts: external_haproxy
  become: true
  vars_files:
    - "inventory/host_variables/{{ ansible_host }}.yml"
  roles:
    - haproxy
  vars:
    haproxy_is_external: true
    haproxy_backend_services:
      homepage:
        mode: http
        balance: roundrobin
        port: 80
        domain_name: jwfh.ca
        servers: 
          - gizmo.lemarchant.jacobhouse.ca
          - bowser.lemarchant.jacobhouse.ca
# - name: Configure ACME.sh certificate management server
#   hosts: acme
#   become: true
#   vars_files:
#     - "inventory/host_variables/{{ ansible_host }}.yml"
#   roles:
#     - acme