---
- name: Public software mirror
  hosts: mirror
  become: true
  vars_files:
    - "inventory/host_variables/{{ ansible_host }}.yml"
  vars:
    nginx_autoindex: true
    nginx_sites:
      - domain_name: mirror.jwfh.ca
        autoindex: true
        all_errors_403: true
    nfs_mounts:
      - server: ritchie
        remote_path: /mnt/default/mirror/www
        local_path: /usr/local/www/sites/mirror.jwfh.ca/www
        mode: ro
  roles:
    - base
    - static-webserver