---
- name: Shlink service
  hosts: shlink
  become: true
  vars_files:
    - "inventory/host_variables/{{ ansible_host }}.yml"
  vars:
    shlink_web_client_dir: /usr/local/www/sites/go-admin.jwfh.ca/www
    sites:
      - domain_name: 'go-admin.jwfh.ca'
        autoindex: false
        all_errors_403: true
  roles:
    - base
    - static-webserver
    - shlink