---
- name: Media Streaming Server
  hosts: streaming
  become: true
  vars_files:
    - "inventory/host_variables/{{ ansible_host }}.yml"
  vars:
    nfs_mounts:
      - server: ritchie
        remote_path: /mnt/default/media/movies
        local_path: /mnt/default/media/movies
        mode: ro
      - server: ritchie
        remote_path: /mnt/default/media/tv
        local_path: /mnt/default/media/tv
        mode: ro
  roles:
    - base
    - plex
    - jellyfin