---
- name: Install dependencies
  package:
    name:
      - python3
      - py311-pipx
      - libxslt
      - libxml2 
      - postgresql16-client
      - rust
      - git-lite
      - pyenv
    state: present
- name: Check if poetry is installed
  stat:
    path: /opt/pipx/venvs/poetry
  register: poetry
- name: Install poetry
  shell:
    cmd: pipx install --global poetry
  when: 'not poetry.stat.exists'
- name: Check if Python is installed by pyenv
  stat:
    path: /opt/pyenv/versions/{{ python_version }}
  register: pyenv_python
- name: Install Python by pyenv
  shell:
    cmd: '`pyenv which python-build` {{ python_version }} /opt/pyenv/versions/{{ python_version }}'
  when: 'not pyenv_python.stat.exists'
- name: Check if Python is sane
  shell:
    cmd: /opt/pyenv/versions/{{ python_version }}/bin/python3 -c 'import sysconfig; print(sysconfig.get_path("platlib"))'
- name: Create .ssh directory for {{ expense_analysis_user }}
  file:
    path: /home/{{ expense_analysis_user }}/.ssh
    state: directory
    owner: '{{ expense_analysis_user }}'
    group: '{{ expense_analysis_group }}'
    mode: '0700'
- name: Create expense-analysis-deployer SSH key in {{ expense_analysis_user }}'s $HOME
  copy: 
    content: "{{ ssm_parameters['expense-analysis-deployer-ssh-private-key'] }}" 
    dest: /home/{{ expense_analysis_user }}/.ssh/expense-analysis-deployer
    owner: '{{ expense_analysis_user }}'
    group: '{{ expense_analysis_group }}'
    mode: '0600'
- name: Create application directory
  file:
    path: '{{ expense_analysis_dir }}'
    state: directory
    owner: '{{ expense_analysis_user }}'
    group: '{{ expense_analysis_group }}'
    mode: '0755'
- name: Mark application directory as safe
  copy:
    content: |-
      [safe]
        directory = {{ expense_analysis_dir }}
    dest: /root/.gitconfig
    owner: 'root'
    group: '{{ wheel }}'
    mode: '0644'
- name: Clone Expense Analysis App with API key
  git:
    repo: 'git@github.com:jwfh/expense-analysis.git'
    dest: '{{ expense_analysis_dir }}'
    version: '{{ expense_analysis_git_ref }}'
    accept_hostkey: true
    key_file: /home/{{ expense_analysis_user }}/.ssh/expense-analysis-deployer
    ssh_opts: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    clone: true
    update: true
    force: true
- name: Fix permissions on application directory
  file: 
    path: '{{ expense_analysis_dir }}'
    owner: '{{ expense_analysis_user }}'
    group: '{{ expense_analysis_group }}'
    mode: u=rwX,g=rX,o=rX
    recurse: true